### ISSUE TITLE
Segmentation fault in checkCollision() at src/object.c:586

### ISSUE THREAD

**Issue by lmarz** [Vasall/vasall-client#10]
I get a segmentation fault in checkCollision() at src/object.c:586. The faulty line is
```c
memcpy(idx, mdl->col.cm_idx[j], INT3_SIZE);
```
Examinig the data in gdb returns
-  `mdl->col.cm_idx[j]` is an invalid address 0x5f4543495645445f
-  `i`,`j` = 0
-  `mdl->name` is plr.
- `idx` is {1789929424, 32765, 4309490}

I've attached the core file. In the project root directory run:
```shell
gzip -d core.gz
gdb ./bin/vasall-client core
(gdb) frame 1
```
Now you can print (command p) the values of the variables
[core.gz](https://github.com/Vasall/vasall-client/files/5709307/core.gz)

**Comment by skratpa** [comment]
As a result of the last big collision-rewrite, a small oversight occurred. Each time the object would update, it would go through the whole list of active objects and then check for collisions. But I didn't implement a clause to prevent objects to check for collisions with themselves. And therefore the player-object tried to process collisions with itself and by doing so tried to load a collision-mesh which aren't attached to player-objects. So the program tried to load data from an invalid address, which caused a segfault.
The problem has been fixed with the latest push.
